### ISSUE TITLE
Not working after adding "Connecting to a Remote User"

### ISSUE THREAD

**Issue by sinisteralex** [adityathakurxd/webrtc_flutter#2]
Not working as intended after adding the code in  "Connecting to a Remote User".

App builds and runs, but just a white screen, as opposed to WebCam-view before said feature is added.

Have you seen this?

**Comment by adityathakurxd** [comment]
Hi, Checked this out. Here's what I did:
- Ran the project on my system to see if there are any updates that need to be

The app worked fine with the video loading as intended. 
Is the permission pop-up to use video and audio showing up for you on web?
