### ISSUE TITLE
Unable to RTCPeerConnection::createAnswer 

### ISSUE THREAD

**Issue by torretorich** [adityathakurxd/webrtc_flutter#4]
i am using my local webSocket
and i try to create answer like this:

```
 RTCSessionDescription? description =
        await _peerConnection?.createAnswer({'offerToReceiveVideo': 1});
    await _peerConnection?.setLocalDescription(description!);
    var data = {
      'type': 'answer',
      'sdp': description?.sdp.toString(),
    };
    sendMessage(data);
```
but i always get pc.connectionState is null
and get this error: peerConnectionCreateAnswer(): WEBRTC_CREATE_ANSWER_ERROR: PeerConnection cannot create an answer in a state other than have-remote-offer or have-local-pranswer.
can you help to solve this?

**Comment by adityathakurxd** [comment]
Hi, Thank you for creating this issue. I updated the package to the latest version and tested it on the web. 
It seemed to work fine. **Is this a platform-specific issue?**

<img width="1512" alt="Screenshot 2023-03-11 at 12 58 21 PM" src="https://user-images.githubusercontent.com/53579386/224471430-b66b2fa8-1a33-4760-87fb-3883d03da0b4.png">

**Comment by adityathakurxd** [comment]
Closing this issue as stale. Let me know if this persists. We can reopen it.
