### ISSUE TITLE
Unclear what should be done after copy-pasting answer in window 1

### ISSUE THREAD

**Issue by akshaydoshi2** [adityathakurxd/webrtc_flutter#6]
Hello, I have developed a project referring to your blog on 100ms.
Although the app runs properly, I'm unable to establish a proper connection between the 2 devices as it's unclear to me what should be done after `Now, click on ‘Answer’ to generate an answer and copy-paste it in the TextField of window 1.`
Should the `set remote description` button be pressed in window 1?

**Comment by adityathakurxd** [comment]
Hi Akshay,
Thank you for creating this issue! Yes, after you generate an answer on Window 2, you can copy-paste it inside the TextField on Window 1 and click on `Set Remote Description`.

**Comment by akshaydoshi2** [comment]
Hey, thanks a lot. Worked perfectly
Closing the thread.
